[[redirects]]
  from = "https://shotsweep.netlify.app/*"
  to = "https://shotsweep.nforshifu234dev.com/:splat"
  status = 301
  force = true

[build.environment]
  PLAYWRIGHT_BROWSERS_PATH = "0"

[functions]
  included_files = [
    "node_modules/playwright-core/.local-browsers/**"
  ]